FROM openjdk:11
MAINTAINER Robert Andersson

ENV QUICKBUILD_HOST=server
ENV QUICKBUILD_USER=admin
ENV QUICKBUILD_PASSWD=quickbuild
ENV QUICKBUILD_URL=

WORKDIR /opt/

RUN apt update && apt install -y python3-pip && apt clean
RUN python3 -m pip install virtualenv

ADD install-tree/ /

CMD /opt/quickbuild/agent.sh console
