FROM openjdk:21-slim
MAINTAINER Robert Andersson

ENV QUICKBUILD_HOST=server
ENV QUICKBUILD_USER=admin
ENV QUICKBUILD_PASSWD=quickbuild
ENV QUICKBUILD_URL=

WORKDIR /opt/

RUN apt update && apt install -y python3-pip python3-virtualenv && apt clean

ADD install-tree/ /

CMD /opt/quickbuild/agent.sh console
