version: "3"

networks:
  quickbuild:

services:
  server:
    build:
      context: .
    image: robrt/quickbuild:latest
    environment:
      - QUICKBUILD_DB_TYPE=postgres
      - QUICKBUILD_DB_HOST=postgres:5432
      - QUICKBUILD_DB_NAME=quickbuild
      - QUICKBUILD_DB_USER=quickbuild
      - QUICKBUILD_DB_PASSWD=quickbuild
    restart: always
    networks:
      - quickbuild
    volumes:
      - quickbuild:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8810:8810"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=quickbuild
      - POSTGRES_PASSWORD=quickbuild
      - POSTGRES_DB=quickbuild
    networks:
      - quickbuild
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
  quickbuild:
