version: "3"

networks:
  quickbuild:

services:
  server:
    build:
      context: .
    image: robrt/quickbuild:latest
    environment:
      - QUICKBUILD_DB_TYPE=h2
    restart: always
    networks:
      - quickbuild
    volumes:
      - quickbuild:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8810:8810"

volumes:
  quickbuild:
