version: "3"

networks:
  quickbuild:

services:
  server:
    build:
      context: .
    image: robrt/quickbuild:latest
    environment:
      - QUICKBUILD_DB_TYPE=h2
    restart: always
    networks:
      - quickbuild
    volumes:
      - quickbuild:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8810:8810"

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    image: robrt/quickbuild-agent:latest
    environment:
      - QUICKBUILD_URL=http://server:8810
      - QUICKBUILD_USER=admin
      - QUICKBUILD_PASSWD=quickbuild
    restart: always
    networks:
      - quickbuild
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - server

volumes:
  quickbuild:
